services:
  go-discord-music:
    build: .
    container_name: go-discord-music
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./playlists.json:/app/playlists.json
